name: Auto Tag Release

on:
  push:
    branches:
      - 'release/*'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag name from branch
        id: extract_tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          TAG_NAME="${BRANCH_NAME#release/}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted tag name: $TAG_NAME"

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse --verify "refs/tags/${{ steps.extract_tag.outputs.tag_name }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.extract_tag.outputs.tag_name }} already exists"
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.extract_tag.outputs.tag_name }} does not exist"
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ steps.extract_tag.outputs.tag_name }}" -m "Release ${{ steps.extract_tag.outputs.tag_name }}"
          git push origin "${{ steps.extract_tag.outputs.tag_name }}"

      - name: Skip tag creation
        if: steps.check_tag.outputs.tag_exists == 'true'
        run: |
          echo "Tag ${{ steps.extract_tag.outputs.tag_name }} already exists, skipping creation"